version: '3.8'
services:
    mongo:
        image: mongo:5
        deploy:
            resources:
                limits:
                    memory: 1G
        ports:
            - 27018:27017
        volumes:
            - mongo-data:/data/db
    service:
        build:
            context: .
            dockerfile: ./ThirteenIsh/Dockerfile
            target: final
        depends_on:
            - mongo
        deploy:
            resources:
                limits:
                    memory: 1G
        env_file:
            - docker.env
            - my.docker.env
volumes:
    mongo-data:

