version: '3.8'
services:
    postgres:
        image: postgres:16
        env_file:
            - my.docker.env
        volumes:
            - postgres-data:/var/lib/postgresql/data
    service:
        build:
            context: .
            dockerfile: ./ThirteenIsh/Dockerfile
            target: final
        depends_on:
            - postgres
        env_file:
            - my.docker.env
volumes:
    postgres-data:

