services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    networks:
      - thirteenish-network
    depends_on:
      - postgres
    env_file:
      - ../my.docker.env

  postgres:
    image: postgres:16
    env_file:
      - ../my.docker.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - thirteenish-network

volumes:
  postgres-data:

networks:
  thirteenish-network: