services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    networks:
      - thirteenish-network
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=thirteenish
      - POSTGRES_PASSWORD=devcontainerpassword
      - DbConnectionString=Host=postgres;Database=thirteenish;Username=thirteenish;Password=devcontainerpassword

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=thirteenish
      - POSTGRES_PASSWORD=devcontainerpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - thirteenish-network

volumes:
  postgres-data:

networks:
  thirteenish-network: